# Speech-commands demo for the M5StickS3.
#
# The board drivers (sticks3, es8311, st7789py, bmi270, m5pm1) are frozen
# into the firmware; only speech_model.py (generated by the browser
# trainer) needs to be uploaded to the device filesystem.
#
# Button A (front, G11): save the current audio snapshot as a training
# sample for the selected label, then reboot.
# Button B (side, G12): cycle through the model's labels.
import gc
import sticks3
import speech_model
import vga1_16x32 as font
from machine import Pin, reset

lcd = sticks3.display()
mic = sticks3.microphone()

def show(*lines):
    lcd.fill(0)
    for i, s in enumerate(lines):
        lcd.text(font, str(s), 10, 10 + 40 * i, 0xFFFF)

# One model inference per 224 ms of audio: 7168 / (16000 * 2) = 0.224
buffer = bytearray(7168)
label = ''
label_index = -1

def save_feature(pin):
    if label_index != -1:
        speech_model.save(speech_model.labels[label_index])
    else:
        speech_model.save(label)
    reset()

def select_label(pin):
    global label_index
    label_index = (label_index + 1) % len(speech_model.labels)
    show(speech_model.labels[label_index])

btn_a, btn_b = sticks3.buttons()
btn_a.irq(handler=save_feature, trigger=Pin.IRQ_FALLING)
btn_b.irq(handler=select_label, trigger=Pin.IRQ_FALLING)
show('Ready!')
print('Ready!')
gc.collect()

while True:
    mic.readinto(buffer)
    l, prob = speech_model.predict(buffer)
    gc.collect()
    if l == '[OTHER]' or prob <= 70:
        continue
    label = l
    speech_model.snapshot()
    print(label, prob)
    show(label, prob)
    # Dispatch commands here, e.g.:
    # if label == 'go':
    #     ...
