# Speech-commands demo for the M5StickS3 — dual-core edition.
#
# Speech recognition runs in a background _thread: the firmware releases
# the GIL during the ~120 ms inference and while mic.readinto() waits on
# DMA, and _thread tasks are free to run on the idle core, so the main
# thread below keeps a robot-control-grade loop (20 ms period) running
# without being stalled by recognition.
#
# The board drivers (sticks3, es8311, st7789py, bmi270, m5pm1) are frozen
# into the firmware; only speech_model.py (generated by the browser
# trainer) needs to be uploaded to the device filesystem.
#
# Button A (front, G11): save the current audio snapshot as a training
# sample for the selected label, then reboot.
# Button B (side, G12): cycle through the model's labels.
import _thread
import gc
import time
import sticks3
import speech_model
from machine import PWM
import vga1_16x32 as font
from machine import Pin, reset

lcd = sticks3.display()
mic = sticks3.microphone()

# Robot control demo: the wheel servos of the Bot HAT live on G5/G4
# (continuous rotation: 1.5ms pulse = stop, 2.0ms = forward at 50 Hz).
wheel_a = PWM(Pin(5), freq=50, duty_ns=1500000)
wheel_b = PWM(Pin(4), freq=50, duty_ns=1500000)

def drive(forward):
    ns = 2000000 if forward else 1500000
    wheel_a.duty_ns(ns)
    wheel_b.duty_ns(ns)

def show(*lines):
    lcd.fill(0)
    for i, s in enumerate(lines):
        lcd.text(font, str(s), 10, 10 + 40 * i, 0xFFFF)

label = ''
label_index = -1
heard = None    # (label, prob), posted by the speech thread
running = True  # cleared on exit so the speech thread ends too

def save_feature(pin):
    if label_index != -1:
        speech_model.save(speech_model.labels[label_index])
    else:
        speech_model.save(label)
    reset()

def select_label(pin):
    global label_index
    label_index = (label_index + 1) % len(speech_model.labels)
    show(speech_model.labels[label_index])

btn_a, btn_b = sticks3.buttons()
btn_a.irq(handler=save_feature, trigger=Pin.IRQ_FALLING)
btn_b.irq(handler=select_label, trigger=Pin.IRQ_FALLING)

def speech_worker():
    global heard
    # Recognition always covers the last ~1 s of audio (61-frame MFCC
    # ring); this chunk is the slide step between evaluations. Inference
    # takes ~115 ms, under the 160 ms step, so recognition stays lossless
    # and real-time (~6 evaluations/s) while running beside the main loop.
    buffer = bytearray(5120)
    while running:
        mic.readinto(buffer)
        l, prob = speech_model.predict(buffer)
        if l != '[OTHER]' and prob > 70:
            speech_model.snapshot()
            heard = (l, prob)
        # Brief yield each cycle: keeps the USB stack and other system
        # tasks serviced while this thread hammers the second core.
        time.sleep_ms(5)

def speech_worker_safe():
    try:
        speech_worker()
    except BaseException as e:
        # Surface thread crashes instead of silently wedging the board.
        print('speech thread died:', repr(e))

show('Ready!')
print('Ready!')
gc.collect()

# Grace period before the speech thread starts: a running _thread blocks
# MicroPython's soft reset, which locks out mpremote / the web IDE. Two
# seconds is enough for tools to interrupt main.py at boot (Ctrl-C).
time.sleep_ms(2000)
_thread.stack_size(24 * 1024)
_thread.start_new_thread(speech_worker_safe, ())

# Main thread: the robot control loop. Servo/encoder work goes here; the
# worst observed loop delay is tracked to show recognition isn't stalling
# it (single-threaded, each inference would freeze this loop for ~120 ms).
PERIOD_MS = 20
DEBOUNCE_MS = 1000  # the ~1s window re-hits a word several times; act once
worst = 0
prev = time.ticks_ms()
last_cmd = -DEBOUNCE_MS
try:
  while True:
    time.sleep_ms(PERIOD_MS)
    now = time.ticks_ms()
    late = time.ticks_diff(now, prev) - PERIOD_MS
    prev = now
    if late > worst:
        worst = late
        print('worst control-loop delay:', worst, 'ms')

    # --- robot control would run here (motors, encoders, sensors) ---

    if heard:
        l, prob = heard
        heard = None
        if time.ticks_diff(now, last_cmd) < DEBOUNCE_MS:
            continue  # same utterance, already handled
        last_cmd = now
        label = l
        # Voice-command dispatch: 'open' drives, 'close' stops.
        if l == 'open':
            drive(True)
            state = 'GO'
        elif l == 'close':
            drive(False)
            state = 'STOP'
        else:
            state = '?'
        print('heard:', l, prob, '->', state)
        show(state, l, prob)
    gc.collect()
finally:
    # On Ctrl-C (or any exit) stop the speech thread so soft reset works
    # and tools can reconnect.
    running = False
    time.sleep_ms(300)
