#!/bin/bash
# Build the speech-commands MicroPython firmware for the M5StickS3
# (ESP32-S3-PICO-1-N8R8: 8MB flash, 8MB octal PSRAM).
#
# The firmware is stock MicroPython plus a `speech_commands` user C module
# built on NNoM (https://github.com/majianjia/nnom): an MFCC front end and a
# convolutional keyword-spotting base model, with a user-trainable dense
# classifier loaded at runtime via speech_commands.init().
#
# Everything is downloaded into ./build (gitignored). Output:
#   ./speech-commands-sticks3.bin  (flash at offset 0x0)
set -euo pipefail

# ESP-IDF manages its own Python environment and refuses to run inside an
# active virtualenv; re-exec with the venv stripped if one is active.
if [ -n "${VIRTUAL_ENV:-}" ]; then
    CLEAN_PATH=$(printf '%s' "$PATH" | tr ':' '\n' | grep -v -F "$VIRTUAL_ENV" | paste -sd: -)
    exec env -u VIRTUAL_ENV PATH="$CLEAN_PATH" "$0" "$@"
fi

cd "$(dirname "$0")"
ROOT="$PWD"
BUILD="$ROOT/build"
mkdir -p "$BUILD"

IDF_VER=v5.4.1
MPY_VER=v1.25.0
NNOM_COMMIT=876b7c8c2b9844e36e9e252404cbc4be1a31e983

if [ ! -f "$ROOT/modules/speech_commands/weights.h" ]; then
    echo "ERROR: modules/speech_commands/weights.h is missing." >&2
    echo "It holds the NNoM keyword-spotting base model (generated by" >&2
    echo "NNoM's model script from a model trained on the Google Speech" >&2
    echo "Commands dataset) and must match the model compiled into the" >&2
    echo "browser trainer's WASM." >&2
    exit 1
fi

# --- ESP-IDF ---
if [ ! -d "$BUILD/esp-idf" ]; then
    git clone -b "$IDF_VER" --depth 1 --recursive --shallow-submodules \
        https://github.com/espressif/esp-idf.git "$BUILD/esp-idf"
fi
if [ ! -d "$HOME/.espressif" ] || ! ls "$HOME/.espressif"/tools/xtensa-esp-elf* >/dev/null 2>&1; then
    "$BUILD/esp-idf/install.sh" esp32s3
fi
set +u
source "$BUILD/esp-idf/export.sh"
set -u

# --- MicroPython ---
if [ ! -d "$BUILD/micropython" ]; then
    git clone -b "$MPY_VER" --depth 1 \
        https://github.com/micropython/micropython.git "$BUILD/micropython"
fi
# Pin tinyusb <0.18: newer versions rename CFG_TUD_CDC_EP_BUFSIZE, breaking
# the esp_tinyusb ~1.0 that MicroPython v1.25 requests.
if ! grep -q "espressif/tinyusb:" "$BUILD/micropython/ports/esp32/main/idf_component.yml"; then
    python3 - "$BUILD/micropython/ports/esp32/main/idf_component.yml" <<'EOF'
import sys
p = sys.argv[1]
s = open(p).read()
pin = '''  espressif/tinyusb:
    rules:
      - if: "target in [esp32s2, esp32s3]"
    version: "<0.18.0"
'''
open(p, 'w').write(s.replace('dependencies:\n', 'dependencies:\n' + pin, 1))
EOF
fi

# --- NNoM ---
if [ ! -d "$BUILD/nnom" ]; then
    git clone https://github.com/majianjia/nnom.git "$BUILD/nnom"
    git -C "$BUILD/nnom" reset --hard "$NNOM_COMMIT"
fi

# --- Build ---
# -Wno-gnu-folding-constant: newer Apple clang errors on MP_STATIC_ASSERT
make -C "$BUILD/micropython/mpy-cross" -j CFLAGS_EXTRA=-Wno-gnu-folding-constant
make -C "$BUILD/micropython/ports/esp32" submodules \
    BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT
make -C "$BUILD/micropython/ports/esp32" -j \
    BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT \
    USER_C_MODULES="$ROOT/modules/speech_commands/micropython.cmake" \
    FROZEN_MANIFEST="$ROOT/manifest.py"

cp "$BUILD/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/firmware.bin" \
    "$ROOT/speech-commands-sticks3.bin"
echo "Built $ROOT/speech-commands-sticks3.bin"
