# MicroPython network module stub for ESP32
from typing import Any, Optional, Union, List, Tuple

class WLAN:
    """WiFi network interface"""
    STA_IF = 0
    AP_IF = 1
    
    def __init__(self, interface_id: int) -> None: ...
    def active(self, is_active: Optional[bool] = None) -> bool: ...
    def connect(self, ssid: Optional[str] = None, password: Optional[str] = None, *, bssid: Optional[bytes] = None) -> None: ...
    def disconnect(self) -> None: ...
    def scan(self) -> List[Tuple[bytes, bytes, int, int, int, int]]: ...
    def status(self, param: Optional[str] = None) -> Any: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, config: Optional[Tuple[str, str, str, str]] = None) -> Tuple[str, str, str, str]: ...
    def config(self, param: str, value: Any = None) -> Any: ...

class LAN:
    """Ethernet LAN interface"""
    def __init__(self, id: int = 0, *, phy_type: int, phy_addr: int, mdc: Any, mdio: Any, power: Any = None, clock_mode: int) -> None: ...
    def active(self, is_active: Optional[bool] = None) -> bool: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, config: Optional[Tuple[str, str, str, str]] = None) -> Tuple[str, str, str, str]: ...
    def config(self, param: str, value: Any = None) -> Any: ...

class PPP:
    """PPP network interface"""
    def __init__(self, id: int) -> None: ...
    def active(self, is_active: Optional[bool] = None) -> bool: ...
    def connect(self, authmode: Optional[int] = None, username: Optional[str] = None, password: Optional[str] = None) -> None: ...
    def disconnect(self) -> None: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, config: Optional[Tuple[str, str, str, str]] = None) -> Tuple[str, str, str, str]: ...

def phy_mode(mode: Optional[int] = None) -> int:
    """Get or set PHY mode"""
    ...

def hostname(name: Optional[str] = None) -> str:
    """Get or set network hostname"""
    ...

def country(code: Optional[str] = None) -> str:
    """Get or set country code"""
    ...

# Constants
STAT_IDLE = 1000
STAT_CONNECTING = 1001
STAT_WRONG_PASSWORD = 202
STAT_NO_AP_FOUND = 201
STAT_CONNECT_FAIL = 203
STAT_GOT_IP = 1010

MODE_11B = 1
MODE_11G = 2
MODE_11N = 3

AUTH_OPEN = 0
AUTH_WEP = 1
AUTH_WPA_PSK = 2
AUTH_WPA2_PSK = 3
AUTH_WPA_WPA2_PSK = 4
